### ISSUE TITLE
Issues with 32bit Architecture (Nintendo 3DS Family)

### ISSUE THREAD

**Issue by ajusa** [treeform/pixie#189]
Hello,

I've been working on getting Pixie to run on the Nintendo 3DS for the last couple of days. After a few changes (and some advice from treeform on Discord) I was able to get it running:

```nim
# (Pixie) paths.nim line 1210
    while x < image.width:
      if x + 4 <= coverages.len:
        let peeked = cast[ptr uint32](coverages[x].addr)[]
        if peeked == 0:
          x += 4
          continue
# (zippy) common.nim line 209
func read64*(s: seq[uint8], pos: int): uint64 {.inline.} =
  # when nimvm:
  (s[pos + 0].uint64 shl 0) or
  (s[pos + 1].uint64 shl 8) or
  (s[pos + 2].uint64 shl 16) or
  (s[pos + 3].uint64 shl 24) or
  (s[pos + 4].uint64 shl 32) or
  (s[pos + 5].uint64 shl 40) or
  (s[pos + 6].uint64 shl 48) or
  (s[pos + 7].uint64 shl 56)
  # else:
    # cast[ptr uint64](s[pos].unsafeAddr)[]

func copy64*(dst: var seq[uint8], src: seq[uint8], op, ip: int) {.inline.} =
  # when nimvm:
  for i in 0 .. 7:
    dst[op + i] = src[ip + i]
  # else:
  #   cast[ptr uint64](dst[op].addr)[] = read64(src, ip)
```
The changes were to avoid getting an "Unaligned" error from the 3DS itself. The 3DS is a 32 bit system, and I was able to fix the errors by avoiding casting to a `ptr uint64`. For Pixie I changed the loop by amount to be a uint32, and for zippy I simply used the existing nimvm implementation. 

Ideally, Pixie would have some way to figure this out at compile time. It could be that when I compiled, I was missing some sort of Nim flag. Here is my `nim.cfg` for reference:

```nim
arm.linux.gcc.path = "/opt/devkitpro/devkitARM/bin"
arm.linux.gcc.exe = "arm-none-eabi-gcc"
arm.linux.gcc.linkerexe = "arm-none-eabi-gcc"
noMain
noLinking
header = "output.h"
cpu = "arm"
os = "linux"
--debugger:native
-d:useMalloc
gc = "arc"
--passC="-specs=3dsx.specs -g -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -Wl,-Map,3dsfun.map   -L/opt/devkitpro/libctru/lib -lctru -lm"
nimcache="../build"
```
Note that pretty much all of the passC flags are from devKitPro, the maintainers of the C toolchain for 3DS.

**Comment by treeform** [comment]
We are aware of this. We are thinking of how to setup the CI to test 32bit. 

For us, we are interested in 32bit mainly because of wasm. Maybe 32bit-ness will be part of some wasm related build.

**Comment by ajusa** [comment]
I've looked into this more, and I think that it also might be an [armv6 alignment issue](https://medium.com/@iLevex/the-curious-case-of-unaligned-access-on-arm-5dd0ebe24965) - just putting that out there. Thanks for the update though, tracking this down is pretty tricky since most people don't actually have 32 bit hardware to test on :smile:

**Comment by treeform** [comment]
It looks like I can make a github action to run it on armv7 which is a 32 bit arm used in Raspberry Pi 2. 

https://github.com/treeform/pixie/runs/2647606163

Not sure if I got it right though...

Does not look like it suffers from the alignment issues that armv6 does?

**Comment by ajusa** [comment]
Interesting, so all of your tests pass. The Raspberry Pi 1 has armv6, not sure if Github actions has that though. Apparently armv6 could toggle whether or not to have alignment issues by setting the value of a register, or by using this gcc flag:
```
-munaligned-access
-mno-unaligned-access
Enables (or disables) reading and writing of 16- and 32- bit values from addresses that are not 16- or 32- bit aligned. By default unaligned access is disabled for all pre-ARMv6, all ARMv6-M and for ARMv8-M Baseline architectures, and enabled for all other architectures. If unaligned access is not enabled then words in packed data structures are accessed a byte at a time.
```
I'll try that, but these values are 64bit rather than 32bit so I'm not sure if that fixes it. I'll edit this issue with the results after testing it.

**Comment by treeform** [comment]
I don't think I got the test right. I wrote little test to point out size and its still 64bit:

```
size of int: 8 bytes
size of cint: 4 bytes
sise of pointer: 8 bytes
endianness of the CPU: littleEndian
```

If you can figure out how to test 32bit stuff with github actions we would use it.

**Comment by ajusa** [comment]
Could you try the same test with `armv6`? https://github.com/uraimo/run-on-arch-action seems to support that as an option.

But yes, I'll look more into that

**Comment by treeform** [comment]
It does not appear to work `run-on-arch: /home/runner/work/_actions/uraimo/run-on-arch-action/v2.0.5/Dockerfiles/Dockerfile.armv6.ubuntu18.04 does not exist.`

**Comment by ajusa** [comment]
armv6 with jessie? See the [matrix table](https://github.com/uraimo/run-on-arch-action#supported-platforms)

Not sure if your tests work on debian though

**Comment by ajusa** [comment]
After doing some more testing on the 3DS, it seems that the only line at which I can get it to reliably crash is
```nim
    cast[ptr uint64](dst[op].addr)[] = read64(src, ip)
``` 
On line 227 of zippy. This is after adding the `-munaligned-access` flag, which might have gotten rid of the crash within Pixie. Still not really sure why this happens though.

**Comment by ajusa** [comment]
I talked with "asie" on Discord about the issue I was running into, and they suggested that it is an alignment error specific to armv6 and potentially the 3DS - unaligned reads aren't allowed at all. Not sure if you want to close this issue, feel free to let me know. I can't expect Pixie to support decade old Nintendo hardware :smile:

**Comment by treeform** [comment]
Thank you for explaining this all to us. 

To keep the scope of this project a little smaller (its already enormous!) we will not be providing support for 3DS hardware with no unaligned-access ability.

Feel free to reopen if you find this issue on more recent hardware.
