### ISSUE TITLE
Context circle helpers that take in a `Circle`

### ISSUE THREAD

**Issue by zetashift** [treeform/pixie#195]
Currently `Context` circle helpers `fillCircle` and `strokeCircle` will only accept a `vec2` and a `float` to make a circle. Any chance of making an overload that adds a  `circle` parameter?

I can make a PR that would just mirror `fillRect`: https://github.com/treeform/pixie/blob/master/src/pixie/context.nim#L158 if that's okay.

**Comment by guzba** [comment]
Ah, great point. I agree we should have a circle helper. If you can make a PR that'd be very welcome of course. Otherwise I'll add it in my next PR of stuff in the next day or two probably. Either way we'll get it in very soon.

**Comment by treeform** [comment]
See: https://github.com/treeform/pixie/pull/196
