### ISSUE TITLE
Issue with image.fillPath with some shapes

### ISSUE THREAD

**Issue by avahe-kellenberger** [treeform/pixie#222]
I noticed I was able to call `fillPath` on rectangles that are taller than longer, but not rectangles that are longer than taller. It may just be a misconception on my part.

Here's a runnable example:

```nim
import pixie

const
  pointsA = [
    vec2(0, 0),
    vec2(0, 1120),
    vec2(32, 1120),
    vec2(32, 0)
  ]
  pointsB = [
    vec2(0, 0),
    vec2(1120, 0),
    vec2(1120, 32),
    vec2(0, 32)
  ]

proc renderPoints(points: openArray[Vec2]): Image =
  let
    image = newImage(1920, 1080)
    ctx = newContext(image)

  ctx.fillStyle = rgba(255, 0, 0, 255)
  var path: Path
  path.moveTo(points[0])
  for v in points:
    path.lineTo(v)

  ctx.image.fillPath(path, ctx.fillStyle)
  return image

when isMainModule:
  # Works
  let imageA = renderPoints(pointsA)
  imageA.writeFile("shapeA.png")

  # Does not work
  let imageB = renderPoints(pointsB)
  imageB.writeFile("shapeB.png")
```

You'll notice `shapeA.png` will have a vertical red rectangle, but `shapeB.png` appears to be empty.

**Comment by guzba** [comment]
I see why this is happening. If you walk the path in your head (or on paper), you'll see you only have 1 vertical line in the 2nd case, but have 2 vertical lines in the first (working) case.  If you close the path (or lineTo the first point at the end), they'll both produce closed paths and render as expected.

What's interesting is JS canvas renders the 2nd path, even though it is not closed. It appears JS is auto-closing paths or something. I'll need to look into what JS canvas/context is doing to match that behavior.

**Comment by avahe-kellenberger** [comment]
Thanks for the insight - for now I'll return back to points[0] as a work around after I've looped over the array

**Comment by guzba** [comment]
Found some docs for SVG that clear this up for me. Quite interesting: 

> The fill operation fills open subpaths by performing the fill operation as if an additional "closepath" command were added to the path to connect the last point of the subpath with the first point of the subpath. Thus, fill operations apply to both open subpaths within ‘path’ elements (i.e., subpaths without a closepath command) and ‘polyline’ elements.

https://svgwg.org/svg2-draft/painting.html

I will adopt this behavior.
