### ISSUE TITLE
Example with GTK 4

### ISSUE THREAD

**Issue by gavr123456789** [treeform/pixie#224]
I see examples for sdl, glfw, glut. Is there an option to use this with GTK?

**Comment by zetashift** [comment]
That would probably look similiar to what is done here: https://github.com/StefanSalewski/gintro#drawing-with-cairo-graphics-library

Is there anything you want to do with GTK and Pixie? Some more specifics can be given that way!

**Comment by treeform** [comment]
@zetashift, I think the @gavr123456789 just wants a port of these examples to GTK:

* https://github.com/treeform/pixie/blob/master/examples/realtime_glfw.nim
* https://github.com/treeform/pixie/blob/master/examples/realtime_glut.nim
* https://github.com/treeform/pixie/blob/master/examples/realtime_sdl.nim
* https://github.com/treeform/pixie/blob/master/examples/realtime_win32.nim
* https://github.com/treeform/pixie/blob/master/examples/realtime_wnim.nim

I don't have any plans to add a GTK real time example sorry. But if some one was to PR one up I would include it.

**Comment by gavr123456789** [comment]
> Is there anything you want to do with GTK and Pixie?  
  
No, all I know is GTK, so to try what pixie is and can it be useful for me, I need the ability to use it with GTK 4.

**Comment by treeform** [comment]
I don't know if a GTK example makes sense. GTK mostly uses Cairo. I think one has to go lower level then that to X11 or Wayland. I don't know enough about Linux GUI programming to do that. I would just use GLFW+OpenGL. Its pretty cross platform and works on Linux/Mac/Windows.

PRs welcome. I will not be adding it though.
