### ISSUE TITLE
Errors when using paths

### ISSUE THREAD

**Issue by avahe-kellenberger** [treeform/pixie#225]
On Nim 1.4.8, pixie#head

`nim r examples/heart.nim`

`pixie/src/pixie/paths.nim(1035, 10) Error: attempting to call undeclared routine: 'isNaN'`

Maybe we should have the ci run the examples?

**Comment by guzba** [comment]
You're running an old version of vmath it appears. Grab the latest and it should be ok. https://github.com/treeform/vmath/

**Comment by avahe-kellenberger** [comment]
Ah interesting. I'll stay on vmath#head with pixie#head, thanks

**Comment by guzba** [comment]
We should up the min version. With the dozen or so repos we're building up on it's a bit daunting to keep everything just right. We've talked about having the examples run too. I think it's easy to add, trying it now here: https://github.com/guzba/pixie/commit/3833a1427799b79b1b4c4fd23713448111e1949a
