### ISSUE TITLE
Realtime GLFW example doesn't work with NimGL's OpenGL and GLFW bindings

### ISSUE THREAD

**Issue by VoNguyenMinhTriet** [treeform/pixie#238]
I'm relatively new to Nim and OpenGL. I copied your real-time GLFW example, modified some identifiers because I don't use staticglfw but NimGL's OpenGL and GLFW bindings. It threw at this line:
```
var dataPtr = ctx.image.data[0].addr
glTexImage2D(GL_TEXTURE_2D, 0, 3, GLsizei w, GLsizei h, 0, GL_RGBA,
    GL_UNSIGNED_BYTE, dataPtr)
```
with traceback: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`
To the best of my knowledge dataPtr is not nil.
Is this an issue on either side or am I just being too ignorant of this?

**Comment by treeform** [comment]
Does the unmodified included glfw example works for you? I just tried it and it works here. Are you on linux, mac or windows?

I don't know why you are getting null pointer, it could be a problem with your code or NimGL. I would print everything out before making that call to make sure that ctx, image, data is not null and w, h are the size of the image.

**Comment by VoNguyenMinhTriet** [comment]
The unmodified version works on my Windows 10.
I also made certain about the texture and image size equality and that `ctx`, `image`, and `data` are not null in my modified version.

**Comment by treeform** [comment]
So this is not really about pixie any more, some thing with your NimGL version is off. Can't really help you with that. Closing. Feel free to reopen if you find its an issue with Pixie.
