### ISSUE TITLE
Invalid YCbCr to RGB calculations

### ISSUE THREAD

**Issue by 89z** [treeform/pixie#241]
Based on ITU-T T.871 [1], the proper equation for YCbCr to RGB looks like this for the red channel:

~~~
R = Y + 1.402 * (Cr - 128)
~~~

or this with rounding:

~~~
R = Min(Max(0, Round(Y + 1.402 * (Cr - 128) )), 255)
~~~

Using this image [2], I wrote a program in Go using the exact formula, taking pixel `X:15,Y:0` just as a test:

~~~go
package main

import (
   "fmt"
   "image"
   "image/jpeg"
   "math"
   "os"
)

func main() {
   f, err := os.Open("Lenna50.jpg")
   if err != nil {
      panic(err)
   }
   defer f.Close()
   picture, err := jpeg.Decode(f)
   if err != nil {
      panic(err)
   }
   pic := picture.(*image.YCbCr).YCbCrAt(15, 0)
   r1 := float64(pic.Y) + 1.402 * float64(pic.Cr - 128)
   r := math.Min(math.Max(0, math.Round(r1)), 255)
   fmt.Println(r1, r) // 220.492 220
}
~~~

Now if I write a similar Nim program, I get a different result:

~~~nim
import pixie

let picture = readImage("Lenna50.jpg")
let pic = picture[15, 0]
echo pic.r # 222
~~~

It seems the Nim example is wrong. Even if Nim rounded up, it would be 221, not 222. I think the code is here:

https://github.com/treeform/pixie/blob/c6ddb736732ae7299012a8137748e28d893b63e3/src/pixie/fileformats/stb_image/stb_image.h#L3559
https://github.com/treeform/pixie/blob/c6ddb736732ae7299012a8137748e28d893b63e3/src/pixie/fileformats/stb_image/stb_image.h#L3585

1. <https://itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.871-201105-I!!PDF-E>
2. https://rosettacode.org/mw/images/3/3c/Lenna50.jpg

**Comment by treeform** [comment]
Sorry this is all related to STB. Does not like like STB is getting fixed for a good reason. Closing this as well.
