### ISSUE TITLE
Does pixie provide image blitting?

### ISSUE THREAD

**Issue by gamecubate** [treeform/pixie#252]
[flippy](https://github.com/treeform/flippy) development has moved to pixie. I needed that library's `blit` functionality.

```
# blit a rectangular part from one place to another
blit(image, image, rect(0, 0, 100, 100), rect(100, 100, 100, 100))
```

Does pixie have an equivalent?

Thx!

**Comment by treeform** [comment]
Yes.

Use the context and `proc drawImage(ctx: Context; image: Image; src, dest: Rect)`: https://nimdocs.com/treeform/pixie/pixie/contexts.html#drawImage%2CContext%2CImage%2Cfloat32%2Cfloat32%2Cfloat32%2Cfloat32%2Cfloat32%2Cfloat32%2Cfloat32%2Cfloat32

**Comment by gamecubate** [comment]
Thanks !
