### ISSUE TITLE
Guidance on usage as a C library

### ISSUE THREAD

**Issue by Sobeston** [treeform/pixie#290]
I can run the tests successfully with `nimble test` but I cannot figure out how to build the library with C bindings.

Genny and pixie have both been installed with `nimble install`. I'm running `nimble bindings pixie.nimble` from a freshly clone of master, but get the following output:

```
$ nimble bindings pixie.nimble
  Executing task bindings in ~/clones/pixie/pixie.nimble
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
.......................................
~/.nimble/pkgs/pixie-2.1.1/pixie/common.nim(21, 14) Warning: use mix instead; lerp is deprecated [Deprecated]
~/.nimble/pkgs/pixie-2.1.1/pixie/common.nim(22, 14) Warning: use mix instead; lerp is deprecated [Deprecated]
~/.nimble/pkgs/pixie-2.1.1/pixie/common.nim(23, 14) Warning: use mix instead; lerp is deprecated [Deprecated]
~/.nimble/pkgs/pixie-2.1.1/pixie/common.nim(24, 14) Warning: use mix instead; lerp is deprecated [Deprecated]
.
~/.nimble/pkgs/pixie-2.1.1/pixie/blends.nim(109, 6) Hint: 'softLight' is declared but not used [XDeclaredButNotUsed]
.....................
~/.nimble/pkgs/pixie-2.1.1/pixie/fileformats/gif.nim(65, 9) Hint: 'colorTableSorted' is declared but not used [XDeclaredButNotUsed]
~/.nimble/pkgs/pixie-2.1.1/pixie/fileformats/gif.nim(66, 9) Hint: 'colorTableSize' is declared but not used [XDeclaredButNotUsed]
~/.nimble/pkgs/pixie-2.1.1/pixie/fileformats/gif.nim(165, 11) Hint: 'extentionType' is declared but not used [XDeclaredButNotUsed]
~/.nimble/pkgs/pixie-2.1.1/pixie/fileformats/gif.nim(31, 5) Hint: 'pixelAspectRatio' is declared but not used [XDeclaredButNotUsed]
~/.nimble/pkgs/pixie-2.1.1/pixie/fileformats/gif.nim(30, 5) Hint: 'bgColorIndex' is declared but not used [XDeclaredButNotUsed]
~/.nimble/pkgs/pixie-2.1.1/pixie/fileformats/gif.nim(28, 5) Hint: 'colorTableSorted' is declared but not used [XDeclaredButNotUsed]
~/.nimble/pkgs/pixie-2.1.1/pixie/fileformats/gif.nim(27, 5) Hint: 'originalDepth' is declared but not used [XDeclaredButNotUsed]
.........
~/clones/pixie/bindings/bindings.nim(46, 13) template/generic instantiation from here
~/clones/pixie/bindings/bindings.nim(47, 6) Error: can raise an unlisted exception: Exception
stack trace: (most recent call last)
/tmp/nimblecache-2590653678/nimscriptapi_3049515398.nim(187, 16)
~/clones/pixie/pixie.nimble(33, 13) bindingsTask
~/clones/pixie/pixie.nimble(22, 10) compile
/usr/lib/nim/system/nimscript.nim(260, 7) exec
/usr/lib/nim/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: nim c -f  -d:release --app:lib --gc:arc --tlsEmulation:off --out:libpixie.so --outdir:bindings/generated bindings/bindings.nim [OSError]
     Error: Exception raised during nimble script execution
```

I'm using Nim 1.4.8 [Linux: amd64], and nimble v0.13.1 on arch linux. I have not used nim before, meaning I cannot progress beyond here. Any guidance on how to build this statically would also be appreciated, though less important.

**Comment by treeform** [comment]
We are working on C bindings but they are just not ready yet, that is way we don't advertise it. Sorry, you probably just came too early. But they should still build!

It looks like the real error is: `Error: can raise an unlisted exception`. I think this is related to us not updating minimum versions of our dependences, we recently cleaned up the exceptions we can raise. What version of Nim do you have? (We use `nim -v`
`Nim Compiler Version 1.4.8`) Its also likely you have older versions of `bumpy`, `chroma` or `vmath`, that don't have the clean up pass. Could you try updating them manually? `nimble uninstall bumpy` and `nimble install bumpy` should do it.

Command to build the bindings is:
`nimble bindings` in the folder of pixie.nimble

That should generate a pixie.h file you could use to dynamically link. We are mainly working on dynamic linking as that's what's other languages python/node/ruby... support.

Thanks for trying us out!

**Comment by Sobeston** [comment]
Just uninstalled and re-installed bumpy, chroma, and vmath. 

My versions:
bumpy: 1.0.3
chroma: 0.2.5
vmath: 1.0.11
nim: 1.4.8

There is no change in output upon running `nimble bindings`.

**Comment by guzba** [comment]
I just set up a new Ubuntu 18 LTS VM and was able to get things to build. The steps were:

1) git clone Pixie repo (not nimble install, that only does tagged releases and bindings is too new for tagged release)
2) nimble install genny (not listed as dep for Pixie since it is only needed to generate bindings)
3) cd to pixie repo dir, run `nimble install` to install dependencies
4) run `nimble bindings` to generate the shared libs and binding files

I am not sure at this point why you're seeing an error since it sounds like you probably went through the same steps.

**Comment by Sobeston** [comment]
Aha, I found the problem. Thanks for helping me through this. The problem was that, in order to run the tests, I had used `nimble install pixie`, causing a version mismatch between the latest on there and the master version. I fixed this by using `nimble uninstall pixie` followed by `nimble install`.

I tried to build it statically by modifying `pixie.nimble` to use `--app:lib` and `compile "libpixie.a"`, which succeeded. However, the symbol "main" ended up in the static library, making it unusable. 

Some issues/annoyances with the generated c bindings:
- size_t is used without importing "stddef.h" (easily fixable compile error)
- long long is used where void* would be appropriate
- some parameters (e.g. file_path in pixie_image_write_file) take mutable pointers, where they should be taking in const pointers.

I've been trying to use this with Zig, but haven't had any luck - images are output from `pixie_image_write_file`, but they're always totally transparent. I'm not sure if I'm misusing the API entirely, or if there's something wrong here. I'm aware that this is almost certainly leaking memory.

```zig
const c = @cImport(@cInclude("pixie.h"));

pub fn main() void {
    const image = c.pixie_new_image(1000, 1000);
    const ctx = c.pixie_image_new_context(image);
    const paint = c.pixie_new_paint(c.PK_SOLID);
    c.pixie_paint_set_color(paint, c.color(0xff, 0xff, 0xff, 0xff));
    c.pixie_paint_set_blend_mode(paint, c.BM_NORMAL);
    c.pixie_context_set_stroke_style(ctx, paint);
    c.pixie_context_set_line_width(ctx, 20);
    c.pixie_context_set_fill_style(ctx, paint);
    c.pixie_context_fill_rect(ctx, 500, 500, 800, 200);

    //ptrToInt and intToPtr used to "strip" the constness of the
    //pointer so that I can pass it in
    c.pixie_image_write_file(image, @intToPtr([*:0]u8, @ptrToInt("output.png")));
}
```

**Comment by guzba** [comment]
Ah great thanks for the update. And thanks for the feedback. The generated C is extremely fresh (like 24-48 hours) and we haven't put together our own tests yet so you're currently our C vanguard :)

We've got a couple personal trips distracting treeform and I for the next week or so, but we're actively working on Pixie and the binding generation so you can expect updates pretty soon.

**Comment by treeform** [comment]
That is progress! 

You can try to `--noMain:off` to generate a "libpixie.a" without main.

Color should probably be: `c.color(1.0f, 1.0f, 1.0f, 1.0f)` the 0xff might be wrapping them to zero some how.

The C output is very raw.

**Comment by Sobeston** [comment]
> You can try to --noMain to generate a "libpixie.a" without main.

This worked! These changes allow me to build statically:
- `compile "libpixie.so"` -> `compile "libpixie.a"`
- `--app:lib` -> `--app:staticlib --noMain`

```
$ file bindings/generated/libpixie.a 
bindings/generated/libpixie.a: current ar archive
```


> Color should probably be: c.color(1.0f, 1.0f, 1.0f, 1.0f) the 0xff might be wrapping them to zero some how.

I forgot that [Zig supports hex floats](https://ziglang.org/documentation/master/#Float-Literals) - having `0xff` compile successfully mislead me into thinking Color was using 8-bit int channels. I passed in a float of 255 here, but I suppose that's unexpected for RGBA channels. 

Changing the code to use `c.color(1, 1, 1, 1)` worked perfectly!

![output](https://user-images.githubusercontent.com/15335529/133203651-01dd524a-cd86-4e88-bbeb-a453805184fd.png)

Some successful source code:

build.zig
```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("pixie", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);

    exe.addLibPath("/pixie-dir/bindings/generated");
    exe.addIncludeDir("/pixie-dir/bindings/generated");
    exe.linkSystemLibrary("pixie");
    exe.linkLibC();
    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```

src/main.zig
```zig
const c = @cImport(@cInclude("pixie.h"));

pub fn main() void {
    const image = c.pixie_new_image(1000, 1000);
    defer c.pixie_image_unref(image);

    const fill_paint = c.pixie_new_paint(c.PK_SOLID);
    defer c.pixie_paint_unref(fill_paint);
    c.pixie_paint_set_color(fill_paint, c.color(1, 0, 0, 1));

    const line_paint = c.pixie_new_paint(c.PK_SOLID);
    defer c.pixie_paint_unref(line_paint);
    c.pixie_paint_set_color(line_paint, c.color(0, 0, 0, 1));

    const fill_paint_2 = c.pixie_new_paint(c.PK_SOLID);
    defer c.pixie_paint_unref(fill_paint_2);
    c.pixie_paint_set_color(fill_paint_2, c.color(1, 1, 1, 1));

    var path_string =
        \\M -1 -12 L 0 -33 C 6 -62 47 -61 47
        \\-34 L 47 0 C 47 5 46 12 43 12 C 30
        \\14 30 13 27 0 L 23 -1 C 19 17 18 14
        \\ 0 13 L -1 -12
    .*;
    const path = c.pixie_parse_path(&path_string);
    defer c.pixie_path_unref(path);

    const transform_matrix = c.Matrix3{ .values = .{
        8,   1,   1,
        1,   8,   1,
        340, 630, 8,
    } };

    c.pixie_image_fill_path(
        image,
        path,
        fill_paint,
        transform_matrix,
        1,
    );
    const seq_float = c.pixie_new_seq_float_32();
    c.pixie_image_stroke_path(image, path, line_paint, transform_matrix, 5, 0, 0, 10, seq_float);

    var path_string_2 =
        \\M 21 -39 C 50 -38 52 -38 53 -31
        \\C 53 -22 49 -23 45 -23 C 41 -23
        \\21 -24 15 -25 C 13 -30 13 -39 21
        \\-39
    .*;
    const path_2 = c.pixie_parse_path(&path_string_2);
    defer c.pixie_path_unref(path_2);

    c.pixie_image_fill_path(
        image,
        path_2,
        fill_paint_2,
        transform_matrix,
        1,
    );
    c.pixie_image_stroke_path(image, path_2, line_paint, transform_matrix, 5, 0, 0, 10, seq_float);

    c.pixie_image_write_file(image, @intToPtr([*:0]u8, @ptrToInt("output.png")));
}
```

I'll leave what it draws a surprise. 

Thanks for all the help! I'll try and get this to link against musl libc another time.

**Comment by treeform** [comment]
Thank you for trying out this with C. We learned some thing to when going over this. 

If you still have issues, feel free to reopen.
