### ISSUE TITLE
Nearest-neighbor scaling

### ISSUE THREAD

**Issue by avahe-kellenberger** [treeform/pixie#291]
Is there a way to scale images with pixie using a nearest neighbor algorithm?

I believe CanvasRenderingContext2D's `imageSmoothingEnabled` property "enables" this behavior

[Wiki link regarding nearest neighbor](https://en.wikipedia.org/wiki/Image_scaling#Nearest-neighbor_interpolation)

If it's simply unimplemented, I could take a stab at it.

--- 

I get the desired effect using `magnifyBy2`, but this seems to create a whole new image.

My ultimate goal is to be able to `scale` the context or image (in similar fashion to `CanvasTransform.scale` in js). There is `proc resize*(srcImage: Image, width, height: int): Image` but this causes blurring.

**Comment by treeform** [comment]
We do nearest-neighbor for nearly all image operations. 

Any rescale will create a new image simply because it has to copy pixies some how from source image to destination. 

Can you give us an example of where the `resize` gives you incorrect blurring? Note: nearly any resize that is not a power of 2 will create some blurring.

**Comment by avahe-kellenberger** [comment]
```nim
import pixie

let img = readImage("king.png")

let 
  newWidth = img.width * 2
  newHeight = img.height * 2

let scaledImg = img.resize(newWidth, newHeight)

img.draw(img)
writeFile(img, "unscaled.png")

scaledImg.draw(scaledImg)
writeFile(scaledImg, "scaled.png")
```

`unscaled.png`
![image](https://user-images.githubusercontent.com/34498340/135687534-b03b7a32-f12f-4eea-8968-c22161693eca.png)


`scaled.png`
![image](https://user-images.githubusercontent.com/34498340/135687707-f4229b6f-4229-4b41-bef6-3d6ffe0ceeba.png)


---

I could be misunderstanding something,
but I expected this to scale with `nearest` instead of a linear scale (which is what seems to be happening).

**Comment by treeform** [comment]
Sorry, I was wrong. We use Bilinear algorithm which averages colors between pixes when scaling. We don't have a way to set nearest mode. But as you noticed you can use magnifyBy2/minnifyBy2 to get the pixel effect.

**Comment by avahe-kellenberger** [comment]
Cool, thanks for the info - I'll close this, then
