### ISSUE TITLE
Realtime Examples Fail Compilation

### ISSUE THREAD

**Issue by 1jss** [treeform/pixie#295]
I'm trying to get the realtime examples to work on macOS 10.15.7

Both `realtime_sdl.nim` and `realtime_glfw.nim` fail compilation with the following output:

    Error: type mismatch: got <ColorRGBX> but expected 'Color = object'

I have installed glfw and sdl:
- `brew install glfw`
- `brew install sdl2{,_gfx,_image,_mixer,_net,_ttf}`

I have installed pixie and nim bindings:
- `nimble install pixie@#head`
- `nimble install staticglfw@#head`
- `nimble install sdl2@#head`

I have also tried with the non-head versions of pixie and bindings.
- `staticglfw` and `sdl2` fails the same way as the head versions
- Non-head `pixie` fails because it misses `newPaint` proc

This works:
- Building the minimal `staticglfw` example without `pixie` works like intended.
- Building other examples like `blur.nim`, `text.nim` and `gradient.nim` works.

What am I missing?

**Comment by treeform** [comment]
Thank you for the bug report. I have fixed the examples here: https://github.com/treeform/pixie/commit/db5a27ef646ed01e0bc9bf009e93b2598bd0296b 

They should work now! Feel free to reopen if they are still not right for you.

**Comment by 1jss** [comment]
Super! I can confirm that both examples now work. Great job!
