### ISSUE TITLE
add font vertical alignment in the context object

### ISSUE THREAD

**Issue by doongjohn** [treeform/pixie#321]
Why is there only a horizontal alignment in the context object?\
Is manually calculating vertical alignment recommended?

**Comment by treeform** [comment]
Are you talking about https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline ?

We still need to implement this feature. You will probably have to compute it manually for now, sorry.

**Comment by treeform** [comment]
We have added textBaseline https://github.com/treeform/pixie/pull/404 

Thank you for opening the issue!
