### ISSUE TITLE
SVG text rendering

### ISSUE THREAD

**Issue by ehmry** [treeform/pixie#338]
`decodeSVG` does not render `text` elements. I think Pixie is good at rendering text so I'm willing to implement this, unless something is blocking it that I don't know about.

**Comment by treeform** [comment]
Sure you could try doing text, but I should warn you text is really really complex. We would want many test cases to prove we are getting it right. If you want to get started on this to see how it goes, thats cool.

**Comment by ehmry** [comment]
Yes, if I manage to get anything done I expect it will be on a topic branch for a long time until it can be validated.

**Comment by ehmry** [comment]
Yea, SVGs are not as good for text as I thought. Not worth the effort to me.
