### ISSUE TITLE
Feature request: Netpbm formats

### ISSUE THREAD

**Issue by nnsee** [treeform/pixie#359]
The FOSS Netpbm project has a few image formats, `.pbm`, `.pgm`, `.ppm`, and `.pnm`. The formats are supported on most Linux distros alongside macOS and Windows. [More reading](https://en.wikipedia.org/wiki/Netpbm). Netpbm formats are commonly used where encoding/decoding speed is crucial but image size is not important.

This is a feature request to support these formats, or at least the most widely used `.ppm`. The format itself is incredibly simple and thus should be simple to implement. For example, take the following dump:
```nim
P3           # "P3" means this is a RGB color image in ASCII
3 2          # "3 2" is the width and height of the image in pixels
255          # "255" is the maximum value for each color
# The part above is the header
# The part below is the image data: RGB triplets
255   0   0  # red
  0 255   0  # green
  0   0 255  # blue
255 255   0  # yellow
255 255 255  # white
  0   0   0  # black
```
The header (file magic, resolution, and maximum value) are ASCII, the actual image data can be bytes (0x00 .. 0xFF) depending on the file magic (type P3 represents ASCII, P6 represents raw bytes). This dump is a textual representation of the following six-pixel image (magnified for demo purposes):
![image](https://user-images.githubusercontent.com/36747857/148247475-02205e1b-16b4-4866-b7d6-e41ad0070568.png)

The official web page for the PPM specification can be found [here](http://netpbm.sourceforge.net/doc/ppm.html).

**Comment by treeform** [comment]
Sorry, I have never seen this format beyond GTK/X11 examples. I think its super rare. I don't think we will be adding support for this any time soon.

But if you want to add support yourself PRs are welcome.

I'll close this for now.

**Comment by nnsee** [comment]
I wouldn't say it's particularly rare, much more common than some of the other formats Pixie supports, such as QOI. It's niche, but it fills that niche space well.

Grim, the reference screenshot utility for Wayland composites, lists PPM as one of the [three output formats it supports](https://github.com/emersion/grim/blob/master/main.c#L328). It's also very common as embedded device splash screens etc.

Nevertheless I understand your viewpoint, and I've no right to demand extra features from any project's maintainer. I will submit a PR (or more) sometime next week.
