### ISSUE TITLE
Why shadow is smaller than the browser's ?

### ISSUE THREAD

**Issue by AmjadHD** [treeform/pixie#376]
if you run this html:
```html
<!DOCTYPE html>
<html>
<body>
<div style="margin: 100px 0px 0px 100px;width: 40px; height: 40px; color: white; box-shadow: 0 2px 8px 1px rgba(0, 0, 0, 0.3)"></div>
</body>
</html>
```
take a screenshot and measure the span of the shadow you'll find it's 60x60
Now:
```nim
proc draw =
  let image = newImage(60, 60)

  let path = newPath()
  path.rect(10, 8, 40, 40)

  let r = newImage(60, 60)
  r.fillPath(path, "white")

  let shadow = r.shadow(
    offset = vec2(0, 2),
    spread = 1,
    blur = 8,
    color = color(0, 0, 0, 0.3)
  )

  image.draw(shadow)
  image.draw(r)
  image.writeFile("pixie_shadow.png")
```
take the image and do the same you'll find it's 56x56 px.
Why ?

**Comment by treeform** [comment]
At first I though It might be blending issues, as browser blends on white background and you are drawing on transparent. But it seems to be not the issue.

It appears that Figma shadows just don't match browser shadows. And we are going by what Figma tells us not the browser. Here are the tests I have done:

![image](https://user-images.githubusercontent.com/125948/152694511-34f7d3e4-45e0-482d-95f0-5a4039db28ed.png)

We match Figma exactly at 8px.

It seems like firfox/chrome/safari don't match the shadows either: 
* https://bugs.chromium.org/p/chromium/issues/detail?id=179006
* https://stackoverflow.com/questions/11167516/different-output-for-same-box-shadow-size-in-chrome-and-firefox
* https://www.wired.com/2011/06/css-3-box-shadow-showcases-browser-differences/
* ....

I don't think browser is a good target, as different ones get you different shadows.

**Comment by treeform** [comment]
I am using Chrome to take that screenshot 98.0.4758.81.

**Comment by treeform** [comment]
I am closing this. We have the correct shadow because we are matching Figma not browser. If the way Figma does it changes we will change too. 

Also the way Figma does it is simple math, we don't have to add any special constants to match. Its strange to me that browser does not match the very simple algorithm.

Feel free to re-open if you disagree.
