### ISSUE TITLE
Repository too large

### ISSUE THREAD

**Issue by locriacyber** [treeform/pixie#378]
So, Nim need to clone the git repository to install pixie. That includes:

20.9 MiB tests/fileformats
16.6 MiB tests/fonts
2.4 MiB docs/banner.png
1.3 MiB examples/data/*

Which I don't need if I don't want to run tests or use some examples. It's slow to download all these.

**Comment by guzba** [comment]
I'm confused:

>Which I don't need if I don't want to run tests or use some examples. 

So you want us to remove the tests and examples from the repo? Sorry but that is insane, Pixie without tests is never going to happen.

What exactly do you suggest we do (that does not involve not having any tests).

**Comment by guzba** [comment]
My guess is the actual issue is not using `git clone --depth 1`

**Comment by locriacyber** [comment]
I am not counting git history size. I think Nimble uses `--depth 1`. Even 35MB is huge.

**Comment by treeform** [comment]
I don't see 35MB in my pixie install folder:

![image](https://user-images.githubusercontent.com/125948/152922096-dc9f9c2a-ffbe-475d-9cc7-2ad277933c05.png)

Please list files in your `~\.nimble\pkgs\pixie-3.1.4`

If you have 35MB there its probably a nimble bug.

**Comment by SolitudeSF** [comment]
35mb is whats getting downloaded by nimble/git, nimble then installs only relevant files. But 35megs is nothing unless you are on heavily metered connection.

**Comment by SolitudeSF** [comment]
dont think thats possible with git

**Comment by treeform** [comment]
I think you can do this with git commands: 

```sh
git archive --remote=ssh://host/pathto/repo.git HEAD README.md
```

But I think github blocks that method so one needs to use the non-git HTTP raw file interface:

```sh
wget https://raw.githubusercontent.com/treeform/pixie/master/src/pixie.nim
```

My point if nimble cared enough they would implement are more efficient download.

**Comment by SolitudeSF** [comment]
> I think you can do this with git commands:
> 
> ```shell
> git archive --remote=ssh://host/pathto/repo.git HEAD README.md
> ```
> 
> But I think github blocks that method so one needs to use the non-git HTTP raw file interface:
> 
> ```shell
> wget https://raw.githubusercontent.com/treeform/pixie/master/src/pixie.nim
> ```
> 
> My point if nimble cared enough they would implement are more efficient download.

that wouldnt work, nimble needs to have directory listing to know which files to install, and that would mean that remote host needs some http interface for per file fetching. thats is some insane amount of care required.

**Comment by guzba** [comment]
I think Nimble using --depth 1 and removing unneeded files is a great middle-ground between download size, final space used and dev effort. Pixie is larger than many libraries to download via git specifically because it needs images for testing (it is a graphics library after ll). So yeah, who cares about some data that downloaded in a few seconds.

No practical suggestions have been forthcoming so closing this.
