### ISSUE TITLE
BMP importer flips red and green channels from some bmp files

### ISSUE THREAD

**Issue by creikey** [treeform/pixie#379]
File which breaks it:
[fromWindows.zip](https://github.com/treeform/pixie/files/8046079/fromWindows.zip)

![image](https://user-images.githubusercontent.com/28424206/153540543-7dab6ec2-cacf-4d28-a689-fdf33a7dc178.png)

It shows up like this in the windows photos viewer, but when ran through pixie like this:
```nim
import pixie, pixie/fileformats/bmp

writeFile("fromPixy.png", encodeImage(decodeBmp(readFile("fromWindows.bmp")), FileFormat.ffPng))
```
![image](https://user-images.githubusercontent.com/28424206/153541075-4a1fd04d-c037-4fb8-9c3c-2b60d394c8e9.png)

The resulting red and blue channels are flipped

**Comment by guzba** [comment]
This should be fixed in Pixie 4.0.0+
