### ISSUE TITLE
Pixie attempts to use SIMD with TCC

### ISSUE THREAD

**Issue by beef331** [treeform/pixie#427]
I know one can use `-d:pixieNoSimd` to get around the issue but may want to consider checking for `tcc` as the C compiler to make it not cause others a problem.
`/home/jason/.cache/nim/mindthegap3d_d/@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sblends.nim.c:9: error: include file 'emmintrin.h' not found`
Is relatively nondescript.

**Comment by guzba** [comment]
Sure we can do that. Added https://github.com/treeform/pixie/pull/428/commits/e9bc2d1322a0ecdd43e5a9df86c6328992b3903b to this pending PR (treeform is traveling now): https://github.com/treeform/pixie/pull/428

**Comment by treeform** [comment]
Thank you for the issues. We have fixes this in our new release. Please try it out :)
