### ISSUE TITLE
Unicode font support

### ISSUE THREAD

**Issue by Nimaoth** [treeform/pixie#462]
Hi, is it possible to render unicode strings containing e.g. emojis somehow? I tried loading a typeface containing emojis but they are not rendered at all, I also tried using that typeface as a fallback for another one but that also didn't work. Any help would be appreciated :^)

**Comment by treeform** [comment]
Sorry we currently do not support emojis.

Its some thing we want to add in the future.

**Comment by Nimaoth** [comment]
Ok, thanks anyways
