### ISSUE TITLE
setColor only does black and white

### ISSUE THREAD

**Issue by iffy** [treeform/pixie#477]
I suspect I'm doing something wrong, but here's what I'm seeing:

```nim
import pixie
let i1 = newImage(10, 10)
i1.setColor(0, 0, color(255, 0, 0, 1))
i1.setColor(1, 1, color(0, 255, 0, 1))
i1.setColor(2, 2, color(0, 0, 255, 1))
i1.writeFile("i1.png")
```

Running that produces a black and white image:
<img width="664" alt="Screen Shot 2022-07-25 at 1 00 01 PM" src="https://user-images.githubusercontent.com/161727/180833818-be3fbb7a-7f95-4856-8949-bceaf1ef2524.png">

How do I set pixel colors with color?

**Comment by guzba** [comment]
I see the issue here: `color()` expects float values from 0 to 1. In this code above you're using 255 for the color channel which but then 1 for the alpha channel. You'll either want to use `color(1, 0, 0, 1)` or `rgba(255, 0, 0, 255)`.

**Comment by iffy** [comment]
derp... Thank you!
