### ISSUE TITLE
suggest to seperate tests and examples from lib 

### ISSUE THREAD

**Issue by retsyo** [treeform/pixie#502]
when we use `nimble install pixie`, the message says `Downloading https://github.com/treeform/pixie using git`. the directory `tests` takes up to 41.6M, so it takes a long time to clone; ok to be honest, I have a bad internet supplier, for most of the time I can't finish `git clone`. I have to download the zipped source, which will be success sometimes, then install by hand. As a result, it is pain for me to install nim's library.

So, I propose to seperate test and examples from pixie lib, as a result we can get a rapid installation of the lib.

thanks

**Comment by guzba** [comment]
Hello and thanks for reporting this. We've actually already done quite a bit of work toward reducing the repo size in the past. This is not a simple problem. Again, this project continuing to work is the most important thing and the tests enable that. If we move the tests to another repo, it is not possible to sync changes to both this repo and that test repo for GitHub Actions. Just as an example of the issues this creates.

Over time we'll be working to improve our custom test set-up which will enable us to improve here. I'm going to close this issue though as we are not going to do specifically what has been requested (removing tests and examples).
