### ISSUE TITLE
Some jpegs that fail to load with "Invalid JPEG, did not get expected restart marker" (pixie 5.0.1)

### ISSUE THREAD

**Issue by sgmihai** [treeform/pixie#503]
Examples
https://m.media-amazon.com/images/M/MV5BOGY5ODdlM2MtNDcwYy00YjJhLTgwYzktMzJhMWYyNTA1NTMzXkEyXkFqcGdeQXVyNTEzMjAxMjE@._V1_.jpg
https://m.media-amazon.com/images/M/MV5BMDI4ZGU1OWYtYTNjMy00YWQ4LTg3M2YtNmUxMDhiZjFhZTYwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjc4MjYzOA@@._V1_.jpg
https://m.media-amazon.com/images/M/MV5BYTdiYWM3ZDQtOGZlYS00MTRmLWI5ZTgtOWNiY2E3NTI2MDgyL2ltYWdlXkEyXkFqcGdeQXVyNTg1MTA0NQ@@._V1_.jpg

they open without a problem everywhere else though, so I'm thinking this is something that should be fixed, no matter what the cause.

**Comment by guzba** [comment]
Thanks for reporting the issue. I'm going to merge this in to one issue instead of three separate ones as it is all related to JPEG progressive & restart markers.

**Comment by guzba** [comment]
https://m.media-amazon.com/images/M/MV5BYjNkYjgwMGYtM2UyYi00ZmRhLTk5MzAtYmU0MDY3ODgzODRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg

**Comment by guzba** [comment]
https://m.media-amazon.com/images/M/MV5BODA3YjY3NmEtMWQ4MC00YmEzLWFkNDQtNjU5ZjNhNjVkYjI0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg
https://m.media-amazon.com/images/M/MV5BNDkyZThhNmMtZDBjYS00NDBmLTlkMjgtNWM2ZWYzZDQxZWU1XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg

**Comment by iffy** [comment]
Oh, I see there's already an issue. I added one to a local failing test if you want it: https://github.com/treeform/pixie/compare/master...iffy:pixie:bad-jpeg

I took a first look at fixing this, but I quickly realized I'll need a lot more jpeg knowledge before I can fix it :)

**Comment by iffy** [comment]
Not all the images posted in this thread fail for the same "did not get expected restart marker" reason.

| Failure | Image |
|---|---|
| Invalid JPEG, did not get expected restart marker | [Image 1 - catherine](https://m.media-amazon.com/images/M/MV5BOGY5ODdlM2MtNDcwYy00YjJhLTgwYzktMzJhMWYyNTA1NTMzXkEyXkFqcGdeQXVyNTEzMjAxMjE@._V1_.jpg) |
| Invalid JPEG, did not get expected restart marker | [Image 2 - world](https://m.media-amazon.com/images/M/MV5BMDI4ZGU1OWYtYTNjMy00YWQ4LTg3M2YtNmUxMDhiZjFhZTYwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjc4MjYzOA@@._V1_.jpg) |
| Invalid JPEG, did not get expected restart marker | [Image 3 - timelives](https://m.media-amazon.com/images/M/MV5BYTdiYWM3ZDQtOGZlYS00MTRmLWI5ZTgtOWNiY2E3NTI2MDgyL2ltYWdlXkEyXkFqcGdeQXVyNTg1MTA0NQ@@._V1_.jpg) |
| Invalid JPEG, invalid chunk marker | [Image 4 - ghosts](https://m.media-amazon.com/images/M/MV5BYjNkYjgwMGYtM2UyYi00ZmRhLTk5MzAtYmU0MDY3ODgzODRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg) |
| Invalid JPEG, unable to load | [Image 5 - queens](https://m.media-amazon.com/images/M/MV5BODA3YjY3NmEtMWQ4MC00YmEzLWFkNDQtNjU5ZjNhNjVkYjI0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg) |
| Invalid JPEG, unable to load | [Image 6 - breaking](https://m.media-amazon.com/images/M/MV5BNDkyZThhNmMtZDBjYS00NDBmLTlkMjgtNWM2ZWYzZDQxZWU1XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg) |
