### ISSUE TITLE
Some jpegs that fail to load with "Invalid JPEG, unable to load" (pixie 5.0.1)

### ISSUE THREAD

**Issue by sgmihai** [treeform/pixie#504]
https://m.media-amazon.com/images/M/MV5BODA3YjY3NmEtMWQ4MC00YmEzLWFkNDQtNjU5ZjNhNjVkYjI0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg
https://m.media-amazon.com/images/M/MV5BNDkyZThhNmMtZDBjYS00NDBmLTlkMjgtNWM2ZWYzZDQxZWU1XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg

**Comment by guzba** [comment]
Merged into https://github.com/treeform/pixie/issues/503
