### ISSUE TITLE
Some jpegs fail to load with "Invalid JPEG, invalid chunk marker" (pixie 5.0.1)

### ISSUE THREAD

**Issue by sgmihai** [treeform/pixie#505]
https://m.media-amazon.com/images/M/MV5BYjNkYjgwMGYtM2UyYi00ZmRhLTk5MzAtYmU0MDY3ODgzODRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg

**Comment by guzba** [comment]
Merged into https://github.com/treeform/pixie/issues/503
