### ISSUE TITLE
When importing library get error

### ISSUE THREAD

**Issue by MrEnder0** [treeform/pixie#507]
```
C:\Users\Ender\Downloads\pixie-master\src\pixie\blends.nim(182, 17) Error: type mismatch: got <Color, Color>
but expected one of:
proc blendSoftLight(backdrop, source: ColorRGBX): ColorRGBX
  first type mismatch at position: 1
  required type for backdrop: ColorRGBX
  but expression 'color(backdrop)' is of type: Color
  ```
This is on
Nim Compiler Version 1.6.6 [Windows: amd64]

**Comment by treeform** [comment]
Make sure you have the most recent version of Chroma and Pixie. Some times nimble is not able to resolve this and it needs to be done manually. You can try nimble uninstall both chroma and pixie and install them again.

On Fri, Sep 23, 2022, at 7:06 PM, Mr.Ender wrote:
> 
> 
> `C:\Users\Ender\Downloads\pixie-master\src\pixie\blends.nim(182, 17) Error: type mismatch: got <Color, Color>
> but expected one of:
> proc blendSoftLight(backdrop, source: ColorRGBX): ColorRGBX
>   first type mismatch at position: 1
>   required type for backdrop: ColorRGBX
>   but expression 'color(backdrop)' is of type: Color
`

**Comment by MrEnder0** [comment]
Yes it seems that the library is fully working after running nimble install chroma.
Thanks!
