### ISSUE TITLE
Missing library crunchy (added in 5.0.5)?

### ISSUE THREAD

**Issue by madasebrof** [treeform/pixie#529]
There is a required library called **`crunchy`** that is missing. It's only used in `png.nim`, but `pixie` is will not install without it!

Based on the name, sounds like a treeform library, but it's not publically available.

This seems odd, as this makes `pixie` fail the basic `nimble install pixie` pretty obviously!

<img width="715" alt="image" src="https://user-images.githubusercontent.com/1993403/224328835-e57d0287-3a08-4898-a23f-130bbf5ac546.png">

**Comment by madasebrof** [comment]
Looks like crunchy was added in 5.05:

https://github.com/treeform/pixie/pull/523/commits/2f8c21a6a9059a44d1d6504df9eaca6994006bdb

**Comment by madasebrof** [comment]
5.0.4 works!

<img width="432" alt="image" src="https://user-images.githubusercontent.com/1993403/224330224-69b78812-75a9-492b-859d-3a139ad66654.png">

**Comment by guzba** [comment]
Crunchy is listed as a dep for Pixie: https://github.com/treeform/pixie/blob/master/pixie.nimble#L15

Confirmed by the build working here: https://github.com/treeform/pixie/commit/317632dd69b0f1624a433b0ab41b0d406ef88084 https://github.com/treeform/pixie/actions/runs/4387604786/jobs/7683101935

Something about Nimble failed (No package found is wrong). Pixie is set up correctly so there is nothing to be done here. Perhaps a caching or config issue locally?
