### ISSUE TITLE
Doesn't run if compiled using nim cpp? (C++)

### ISSUE THREAD

**Issue by madasebrof** [treeform/pixie#530]
Just checking, was wanting to use `pixie` as part of a larger program, but this program gets compiled to cpp. (I'm heavily using a cpp library, so need to output cpp)

I get errors with `pixie` if I try to compile with `nim cpp`. Not sure if this is like "yeah, we know, too hard to support compiling to C++", or if on the roadmap, or if there is some magic work around.

Thanks!!!

**Comment by madasebrof** [comment]
Whoops, just found closed issue, closing now...

**Comment by treeform** [comment]
You can see here https://github.com/treeform/pixie/blob/master/.github/workflows/build.yml#L22 that we test with `nim cpp` on every commit on Mac, Linux and Windows. We fully support C++ compilation.
