### ISSUE TITLE
The API Reference documentation appears to be down

### ISSUE THREAD

**Issue by finitemonkey** [treeform/pixie#532]
The API Reference documentation at https://nimdocs.com/treeform/pixie appears to be having a problem of some sort.   

I am getting sometimes "A timeout occurred.  Error code 524" from Cloudflare.com and sometimes a simple "Not found" message.

Or possibly there is no actual problem with the docs, maybe the documentation was moved at some point and the link in the [README.md](https://github.com/treeform/pixie/blob/f3e73f722fbb0e5d496fbc59ee860a9fd49983de/README.md) just needs updating?

**Comment by guzba** [comment]
Thanks for pointing this out, I've fixed this at least for now.
