### ISSUE TITLE
Help: readImage from memory

### ISSUE THREAD

**Issue by konsumer** [treeform/pixie#534]
I'd like to use physfs to read image files for a mounted archive, but didn't see anything to read memory-pointer/length or a string of bytes, instead of file for `readImage`. How do I do this?

**Comment by konsumer** [comment]
Sorry for noise. I saw [readImage](https://github.com/treeform/pixie/blob/f3e73f722fbb0e5d496fbc59ee860a9fd49983de/src/pixie.nim#L69-L74).

Looks like I can do:

```nim
try:
  decodeImage(stringOfFileData)
except IOError as e:
  raise newException(PixieError, e.msg, e)
```

**Comment by guzba** [comment]
No problem at all, yeah `decodeImage` is the best option right now.

It would probably be reasonable to do an `openArray[byte]` update instead of strictly `string` to enable ptr+len and other other stuff without copying. Mind as well put that on my future improvements list.

**Comment by konsumer** [comment]
Sounds good. I am using string memory-location and stuff, so I think it's still 0-copy, but I am kinda new to nim, so I may be doing/understanding it wrong.


For others looking for similar:

- [Here](https://github.com/notnullgames/null0-pixie/blob/d8c6b697b5d9174aee0400300d8d166f302ca367/src/null0pkg/physfs.nim) is my physfs wrapper.
- Make sure to init/mount your zip/etc like [this](https://github.com/notnullgames/null0-pixie/blob/d8c6b697b5d9174aee0400300d8d166f302ca367/src/null0pkg/api.nim#L51-L57)
- I made a very small `readImagePhysfs` [here](https://github.com/notnullgames/null0-pixie/blob/d8c6b697b5d9174aee0400300d8d166f302ca367/src/null0pkg/imports/image.nim#L8-L9)

This all fits together great!
