### ISSUE TITLE
Need a way to access Font.typeface.opentype

### ISSUE THREAD

**Issue by TakWolf** [treeform/pixie#539]
We need use OpenType object (use opentype tables like hmtx, cmap).

See: https://github.com/TakWolf/nico-font-tool/blob/b37c4ac5b48e6f052120821b582ff90591259fd8/src/nico_font_tool.nim#L21

```
  let fontFileExt = splitFile(fontFilePath).ext.toLowerAscii
  if fontFileExt != ".otf" and fontFileExt != ".ttf":
    raise newException(CatchableError, "Unsupported font format")
  let openType = parseOpenType(readFile(fontFilePath))              # <-------
  let font = readFont(fontFilePath)     # <-------   loaded twice
  font.size = float32(fontSize)
  echo "loaded font file: ", fontFilePath
```

Or gave a way to create Typeface use OpenType

**Comment by treeform** [comment]
Also note that Typeface is a very thin wrapper: https://github.com/treeform/pixie/blob/master/src/pixie/fonts.nim#L11-L15 you can create Typeface around an OpenType object yourself https://github.com/treeform/pixie/blob/master/src/pixie/fonts.nim#L686-L702 .

I hope that helps!

**Comment by TakWolf** [comment]
The current problem is:  we can't create a Typeface object directly with a OpenType object. Like:

```nim
let openType = parseOpenType(readFile(fontFilePath))
let typeface = Typeface()
typeface.opentype = parseOpenType(buf)     # <--- This is impossible, because opentype is not open.
```

And there is no proc like:

```nim
proc newFromOpenType*(opentype: OpenType): Typeface =
  result = Typeface()
  result.opentype = opentype
```

Library only have one this proc to create OpenType Typeface:

https://github.com/treeform/pixie/blob/master/src/pixie/fonts.nim#L501-L504

Now, we do like this:

```nim
let openType = parseOpenType(readFile(fontFilePath))
let font: TypeFace = readFont(fontFilePath)
```

This can indeed run, but strictly, this is not the best.
The font has actually been loaded twice.

**Comment by treeform** [comment]
There is a function to create a Font from a typeface: https://github.com/treeform/pixie/blob/master/src/pixie/fonts.nim#L208

```nim
let openType = parseOpenType(readFile(fontFilePath))
let font: TypeFace = readFont(openType)
```

No need for double read.
