### ISSUE TITLE
The API docs are down and/or overloaded

### ISSUE THREAD

**Issue by finitemonkey** [treeform/pixie#540]
https://nimdocs.com/treeform/pixie/ is timing out again, "Error code 524".

The error page also says; "The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application."

**Comment by guzba** [comment]
Thanks for reporting this. We have moved the docs to https://treeform.github.io/pixie/ and updated the readme etc. (nimdocs.com is going away.)
