### ISSUE TITLE
[Question] Using pixie during compilation phase

### ISSUE THREAD

**Issue by mantielero** [treeform/pixie#543]
Do you think `pixie` could be used to read images during the compilation phase?

I was looking into [readImage](https://github.com/treeform/pixie/blob/523b364fcaa288d23ecb3f34c795da97d3637117/src/pixie.nim#L81-L86) and I was wondering if using [staticRead](https://forum.nim-lang.org/t/10318) would be sufficient. The idea would be to add a `staticReadImage` proc using `staticRead`.

What am I looking for? I am spending some time in this project: [lvgl.nim](https://github.com/mantielero/lvgl.nim). When dealing with images, [it requires converting the images to C arrays](https://docs.lvgl.io/master/widgets/img.html). For that, they set this [web page](https://lvgl.io/tools/imageconverter). I'd like to avoid that and to create the array directly in Nim during the compilation phase.

**Comment by guzba** [comment]
Sorry, no Pixie is not intended to be used during the compilation phase and making this work would not be as easy as using staticRead. Especially not for JPEG and PNG. This is not something that will be supported in Pixie, sorry.
