### ISSUE TITLE
about clockwise

### ISSUE THREAD

**Issue by haoyu234** [treeform/pixie#548]
https://github.com/treeform/pixie/blob/2ce0404922fe5e23a03c4af3cf84cb547ea84b1d/src/pixie/paths.nim#L506-L509

I noticed the description here about the clockwise parameter, as far as I know only non-zero padding is related to the path direction, is it described wrong here?

**Comment by treeform** [comment]
Your right the doc is wrong. Actually you can use both non-zero and even-odd winding rules to cut out a path, so it should not even mention that. The doc should say some thing like:

## Clockwise param can be used to subtract a rect from another rect, when paths have different winding orders.

Maybe I should draw my own version of https://help.adobe.com/en_US/as3/dev/images/gv_winding_rules_evenodd_nonzero.png and add that to pixie book. https://github.com/treeform/pixiebook
