### ISSUE TITLE
Crash when calling image.fill() with SIMD

### ISSUE THREAD

**Issue by Anuken** [treeform/pixie#58]
Calling fill() on an image causes a crash in certain situations. I encountered this issue when loading/rendering in `typography`.

Stack trace looks something like this:

```
typography-0.7.2/typography/rasterizer.nim(297) getGlyphImage
typography-0.7.2/typography/rasterizer.nim(292) getGlyphImage
typography-0.7.2/typography/rasterizer.nim(109) getGlyphImage
pixie/src/pixie/images.nim(85) fill

SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

[This line](https://github.com/treeform/pixie/blob/master/src/pixie/images.nim#L85) causes the segfault.
[According to StackOverflow](https://stackoverflow.com/a/43204755), when using `_mm_store_si128`, "The destination address needs to be 16 byte aligned." 

I could very well be wrong, but there doesn't seem to be anything guaranteeing that image data is 16-byte aligned. Switching to `_mm_storeu_si128` fixes the problem.

**Comment by Anuken** [comment]
Update: Appears to happen for all invert() too, even after e9d340d6a4a62b00117f7a3151e1e153251385a7. 

Reproduction steps:

```
import pixie, random, chroma

for i in 0..1000:
  let img = newImage(1 + rand(10), 1 + rand(10))
  img.fill(rgba(1, 1, 1, 0)) #crashes
  img.invert() #also crashes
```

**Comment by guzba** [comment]
Thanks for the repro example. I've given it a run a bunch of times while using the aligned mm_load_ mm_store_ intrinsics and never had any issue. I'm on 64 bit Intel, + Windows. Tried GCC and VCC compilers. Do you have some difference that could be part of this?

In the meantime I am switching to using the unaligned intrinsics to be safe but I'd like to try to figure out why this is happening for you but not me if possible.

**Comment by guzba** [comment]
Also, very old post about this just for record here: https://forum.nim-lang.org/t/255

**Comment by Anuken** [comment]
I'm using 64-bit Ubuntu (20.04), GCC, AMD Ryzen 7 3800X, Nim 1.4.2 - rather different from your system. I'm not experienced enough with this stuff to say which one of those could be the cause of this discrepancy, though.

When I run the code from the post:

`(cast[uint64](addr(image.data[0])) and 0b1_0000) == 0b1_0000`

...I get `false`. So the data seq is indeed misaligned.

> it's aligned to 16 bytes due to sheer luck.

I guess my luck ran out?

**Comment by guzba** [comment]
I'm not sure either but I'd certainly rather be using the unaligned and have things work that's for sure lol. I may dig into this more but for now at least I know the seq is not aligned anymore (at least not for all circumstances).

**Comment by guzba** [comment]
0.0.14+ should fix this. Looks like it'll by typography 0.7.3+ too

**Comment by Anuken** [comment]
Thanks! I can confirm that it doesn't crash as of 0.0.14.

However, now I'm running into another issue: `blends.nim` [uses SIMD instructions](https://github.com/treeform/pixie/blob/master/src/pixie/blends.nim#L291) that are not gated behind a `amd64` check. This leads to failure of my WebAssembly builds [1]. I don't have any ARM builds set up, but those would likely fail as well.

These changes were first introduced in commit 8ef4b3ecc8dde5302b93632a47dc0828869d1f42. Should I try and make a PR that uses the non-SIMD implementation when applicable?

---

*[1]: Technically, WASM does support SIMD, but it's gated behind a special compiler flag and has poor browser support.*
